# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      # with:
      #   ref: dev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clone shijl0925/sonarqube-gen repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'shijl0925'
        repository: 'sonarqube-gen'

    - name: Build sonarqube-gen
      run: |
        cd sonarqube-gen
        go build -v -o main ./...
        mkdir sonarqube
        ./main --host="https://next.sonarqube.com/sonarqube" --internal=false

    - name: Rewrite code 
      run: |
        cp -r sonarqube-gen/sonarqube ./
        rm -rf sonarqube-gen/
        git diff

    - name: Create commits
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          date +%s > report.txt
          git add -A
          git commit -m "Add untracked file during workflow"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
          token: ${{ secrets.PAT }}

    # - name: Create Pull Request
    #   run: gh pr create -B master -H dev --title 'Merge dev into master' --body 'Created by Github action'
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
