# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron:  '0 1 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clone shijl0925/sonarqube-gen repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'shijl0925'
        repository: 'sonarqube-gen'

    - name: Build sonarqube-gen
      run: |
        cd sonarqube-gen
        go build -v -o main ./...
        mkdir sonarqube
        ./main --host="https://next.sonarqube.com/sonarqube" --internal=false

    - name: Rewrite code 
      run: |
        cp -r sonarqube-gen/sonarqube ./
        rm -rf sonarqube-gen/
        git diff

    - name: Test
      run: |
        # go test -v ./...
        cd examples
        go run get_components.go
        go run get_duplications.go
        go run get_issue_changelog.go
        go run get_issues.go
        go run get_source.go
        go run get_version.go

    - name: Create commits
      uses: EndBug/add-and-commit@v9
      with:
        message: Add untracked file during workflow
        committer_name: GitHub Actions
        committer_email: actions@github.com
        push: false

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
          token: ${{ secrets.PAT }}
