# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clone shijl0925/sonarqube-gen repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'shijl0925'
        repository: 'sonarqube-gen'

    - name: Build sonarqube-gen
      run: |
        cd sonarqube-gen
        go build -v -o main ./...
        mkdir sonarqube
        ./main --host="https://next.sonarqube.com/sonarqube" --internal=false

    - name: Rewrite code 
      run: |
        cp -r sonarqube-gen/sonarqube ./
        rm -rf sonarqube-gen/
        git status
        git diff
